In [1]:
documents = ["Learning Python programming is fast as Python is easy",
             "Python is great programming language"]

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

max_features=3
tfidf_vectorizer = TfidfVectorizer(max_features=max_features)
tfidf_vectors = tfidf_vectorizer.fit_transform(documents)
vectors = tfidf_vectorizer.fit_transform(documents)
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6 stored elements and shape (2, 3)>
  Coords	Values
  (0, 2)	0.6666666666666666
  (0, 1)	0.3333333333333333
  (0, 0)	0.6666666666666666
  (1, 2)	0.5773502691896258
  (1, 1)	0.5773502691896258
  (1, 0)	0.5773502691896258

In [3]:
feature_names = tfidf_vectorizer.get_feature_names_out()
print("Feature Names:")
print(feature_names)

Feature Names:
['is' 'programming' 'python']

In [4]:
print(vectors.toarray())

[[0.66666667 0.33333333 0.66666667]
 [0.57735027 0.57735027 0.57735027]]

In [5]:
import pandas as pd

example_df=pd.DataFrame(data=tfidf_vectors.toarray(),columns=feature_names)
example_df

         is  programming    python
0  0.666667     0.333333  0.666667
1  0.577350     0.577350  0.577350

In [6]:
documents = ["Learning Python is easy",
             "CSharp is great programming language"]

max_features=3

tfidf_vectorizer = TfidfVectorizer(max_features=max_features)
tfidf_vectors = tfidf_vectorizer.fit_transform(documents)

feature_names = tfidf_vectorizer.get_feature_names_out()

vectors = tfidf_vectorizer.fit_transform(documents)
example_df=pd.DataFrame(data=tfidf_vectors.toarray(),columns=feature_names)
example_df

     csharp      easy        is
0  0.000000  0.814802  0.579739
1  0.814802  0.000000  0.579739